ChromeRigs.MVC/Controllers/CustomersController.cs
using AutoMapper;
using ChromeRigs.Entities.Customers;
using ChromeRigs.MVC.Data;
using ChromeRigs.MVC.Models.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ChromeRigs.MVC.Controllers
{
    public class CustomersController : Controller
    {
        #region Data & Const

        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CustomersController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        #endregion

        #region Actions
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var customers = await _context
                                    .Customers
                                    .ToListAsync();


            var customerVMs = _mapper.Map<List<CustomerViewModel>>(customers);

            return View(customerVMs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context
                                        .Customers
                                        .Include(customer => customer.Orders)
                                        .Where(customer => customer.Id == id)
                                        .SingleOrDefaultAsync();
            if (customer == null)
            {
                return NotFound();
            }

            var customerDetailsVM = _mapper.Map<CustomerDetailsViewModel>(customer);

            return View(customerDetailsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUpdateCustomerViewModel createUpdateCustomerViewModel)
        {
            if (ModelState.IsValid)
            {
                var customer = _mapper.Map<Customer>(createUpdateCustomerViewModel);

                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(createUpdateCustomerViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }

            var createUpdateCustomerViewModel = _mapper.Map<CreateUpdateCustomerViewModel>(customer);

            return View(createUpdateCustomerViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateUpdateCustomerViewModel createUpdateCustomerViewModel)
        {
            if (id != createUpdateCustomerViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var customer = await _context
                                    .Customers
                                    .FindAsync(id);

                if (customer == null)
                {
                    return NotFound();
                }

                _mapper.Map(createUpdateCustomerViewModel, customer);

                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(createUpdateCustomerViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(createUpdateCustomerViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Private Methods

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }

        #endregion
    }
}

ChromeRigs.MVC/Controllers/OrdersController.cs
using AutoMapper;
using ChromeRigs.Entities.Orders;
using ChromeRigs.Entities.PCs;
using ChromeRigs.MVC.Data;
using ChromeRigs.MVC.Models.Orders;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ChromeRigs.MVC.Controllers
{
    public class OrdersController : Controller
    {
        #region Data & Const

        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public OrdersController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            this._mapper = mapper;
        }

        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var orders = await _context
                                .Orders
                                .Include(order => order.Customer)
                                .ToListAsync();

            var orderVMs = _mapper.Map<List<OrderViewModel>>(orders);

            return View(orderVMs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context
                                    .Orders
                                    .Include(order => order.Customer)
                                    .Include(order => order.PCs)
                                    .Where(order => order.Id == id)
                                    .SingleOrDefaultAsync();


            if (order == null)
            {
                return NotFound();
            }

            var orderDetailsVM = _mapper.Map<OrderDetailsViewModel>(order);

            return View(orderDetailsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createUpdateOrderVM = new CreateOrderViewModel();

            createUpdateOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            createUpdateOrderVM.PCLookUp = new MultiSelectList(_context.PCs, "Id", "Name");

            return View(createUpdateOrderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOrderViewModel createOrderVM)
        {
            if (ModelState.IsValid)
            {
                var order = _mapper.Map<Order>(createOrderVM);

                order.OrderTime = DateTime.Now;

                await UpdateOrderPCs(order, createOrderVM.PCIds);

                order.TotalPrice = GetOrderTotalPrice(order.PCs);

                _context.Add(order);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            createOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            createOrderVM.PCLookUp = new MultiSelectList(_context.PCs, "Id", "Name");

            return View(createOrderVM);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context
                                    .Orders
                                    .Include(order => order.PCs)
                                    .Where(order => order.Id == id)
                                    .SingleOrDefaultAsync();

            if (order == null)
            {
                return NotFound();
            }

            var updateOrderVM = _mapper.Map<UpdateOrderViewModel>(order);

            updateOrderVM.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            updateOrderVM.PCLookUp = new MultiSelectList(_context.PCs, "Id", "Name");

            return View(updateOrderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateOrderViewModel updateViewModel)
        {
            if (id != updateViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Get the order including PCs from the DB
                var order = await _context
                                        .Orders
                                        .Include(order => order.PCs)
                                        .Where(order => order.Id == id)
                                        .SingleOrDefaultAsync();

                if (order == null)
                {
                    return NotFound();
                }

                // Patch the order
                _mapper.Map(updateViewModel, order);

                // Update Order PC
                await UpdateOrderPCs(order, updateViewModel.PCIds);

                // Update Order Total Price
                order.TotalPrice = GetOrderTotalPrice(order.PCs);

                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(updateViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            updateViewModel.CustomerLookup = new SelectList(_context.Customers, "Id", "FullName");
            updateViewModel.PCLookUp = new MultiSelectList(_context.PCs, "Id", "Name");

            return View(updateViewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Private Methods

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }

        private async Task UpdateOrderPCs(Order order, List<int> pcIds)
        {
            order.PCs.Clear();

            var pcs = await _context
                                .PCs
                                .Where(pc => pcIds.Contains(pc.Id))
                                .ToListAsync();

            order.PCs.AddRange(pcs);
        }

        private decimal GetOrderTotalPrice(List<PC> pcs)
        {
            var pcsPrice = pcs.Sum(pc => pc.Price);
            var pcsPriceWithProfit = pcsPrice * 1.25m;

            return pcsPriceWithProfit;
        }

        #endregion
    }
}

ChromeRigs.MVC/Controllers/PCsController.cs
using AutoMapper;
using ChromeRigs.Entities.Components;
using ChromeRigs.Entities.PCs;
using ChromeRigs.MVC.Data;
using ChromeRigs.MVC.Models.PCs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ChromeRigs.MVC.Controllers
{
    public class PCsController : Controller
    {
        #region Data & Const

        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public PCsController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        #endregion

        #region Actions

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var pcs = await _context.PCs.ToListAsync();
            var pcVMs = _mapper.Map<List<PCViewModel>>(pcs);
            return View(pcVMs);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var pc = await _context
                                .PCs
                                .Include(pc => pc.Components)
                                .Where(pc => pc.Id == id)
                                .SingleOrDefaultAsync();

            if (pc == null) return NotFound();

            var pcVM = _mapper.Map<PCDetailsViewModel>(pc);
            return View(pcVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createUpdatePCVM = new CreateUpdatePCViewModel();
            createUpdatePCVM.ComponentLookup = new MultiSelectList(_context.Components, "Id", "Name");
            return View(createUpdatePCVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUpdatePCViewModel createUpdatePCViewModel)
        {
            if (ModelState.IsValid)
            {
                var pc = _mapper.Map<PC>(createUpdatePCViewModel);
                await UpdatePCComponents(pc, createUpdatePCViewModel.ComponentsIds);
                pc.Price = GetPCPrice(pc.Components);
                _context.Add(pc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(createUpdatePCViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var pc = await _context
                                .PCs
                                .Include(pc => pc.Components)
                                .Where(pc => pc.Id == id)
                                .SingleOrDefaultAsync();

            if (pc == null) return NotFound();

            var pcVM = _mapper.Map<CreateUpdatePCViewModel>(pc);
            pcVM.ComponentLookup = new MultiSelectList(_context.Components, "Id", "Name");

            return View(pcVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateUpdatePCViewModel createUpdatePCViewModel)
        {
            if (id != createUpdatePCViewModel.Id) return NotFound();

            if (ModelState.IsValid)
            {
                var pc = await _context
                                    .PCs
                                    .Include(pc => pc.Components)
                                    .Where(pc => pc.Id == id)
                                    .SingleOrDefaultAsync();

                if (pc == null) return NotFound();

                _mapper.Map(createUpdatePCViewModel, pc);
                await UpdatePCComponents(pc, createUpdatePCViewModel.ComponentsIds);
                pc.Price = GetPCPrice(pc.Components);

                try
                {
                    _context.Update(pc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PCExists(createUpdatePCViewModel.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(createUpdatePCViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pc = await _context.PCs.FindAsync(id);
            if (pc != null) _context.PCs.Remove(pc);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Private Methods

        private bool PCExists(int id)
        {
            return _context.PCs.Any(e => e.Id == id);
        }

        private async Task UpdatePCComponents(PC pc, List<int> componentsIds)
        {
            pc.Components.Clear();

            var components = await _context
                .Components
                .Where(c => componentsIds.Contains(c.Id))
                .ToListAsync();

            pc.Components.AddRange(components);
        }

        private decimal GetPCPrice(List<Component> components)
        {
            var pcPrice = components.Sum(component => component.Price);
            var pcPriceWithProfit = pcPrice * 1.4m;

            return pcPriceWithProfit;
        }

        #endregion
    }
}

ChromeRigs.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChromeRigs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.datatables.net/2.1.7/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" integrity="sha512-6lLUdeQ5uheMFbWm3CP271l14RsX1xtx+J5x2yeIDkkiBpeVTNhTqijME7GgRKKi6hCqovwCoBTlRBEC20M8Mg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/ChromeRigs.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand fw-bold text-chromerigs-color" title="Home Page" asp-area="" asp-controller="Home" asp-action="Index">
                    <img height="40px" class="align-content-center" src="/imgs/chromerigs.png" />
                    ChromeRigs
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Components" asp-action="Index">Components</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PCs" asp-action="Index">PCs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer>

        <div class="site-map">

            <div class="container py-5">

                <div class="row g-4">

                    <div class="col-lg-6 col-xl-3">

                        <div class="text-body-secondary">
                            <h3 class="text-dark">ChromeRigs</h3>
                            <div>441-1001, Nishishinjuku Shinjuku Sukueatawa(24-kai)</div>
                            <div>Tokyo, Shinjuku-ku</div>
                            <div>Japan</div>

                            <div class="mt-4">
                                <label for="phone" class="fw-bold">Phone:</label>
                                <a id="phone" class="text-decoration-none text-chromerigs-color a-hover"
                                   href="tel:+81000000000">+81000000000</a>
                            </div>
                            <div>
                                <label for="email" class="fw-bold">Email:</label>
                                <a id="email" class="text-decoration-none text-chromerigs-color a-hover"
                                   href="mailto:chromerigs@gmail.com">chromerigs@gmail.com</a>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Useful Links</h6>

                        <ul class="nav flex-column">
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Home
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    About Us
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Services
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Term of Service
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Privacy Policy
                                </a>
                            </li>
                        </ul>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Our Services</h6>

                        <ul class="nav flex-column">
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Home
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    About Us
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Services
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Term of Service
                                </a>
                            </li>
                            <li class="nav-item mb-2">
                                <a href="#" class="nav-link p-0 text-body-secondary">
                                    <i class="fa-solid fa-chevron-right text-chromerigs-color me-1"></i>
                                    Privacy Policy
                                </a>
                            </li>
                        </ul>

                    </div>

                    <div class="col-lg-6 col-xl-3">

                        <h6 class="fw-bold mb-3">Follow us on Social Media</h6>
                        <p>Monthly updates on new Codes, Components, PC's ETC!'.</p>

                        <div class="social-links d-flex gap-2">

                            <a href="https://www.x.com" target="_blank" class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-x-twitter"></i>
                            </a>

                            <a href="https://www.facebook.com" target="_blank"
                               class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-facebook"></i>
                            </a>

                            <a href="https://www.instagram.com" target="_blank"
                               class="social-link text-light rounded-circle">
                                <i class="fa-brands fa-instagram"></i>
                            </a>
                        </div>

                    </div>

                </div>

            </div>

        </div>

        <div class="copy-right bg-section">

            <div class="container">

                <div class="d-flex justify-content-between fs-7 py-3">

                    <div>
                        &copy; Copyright <span class="fw-bold">ChromeRigs.</span> All Rights Reserved.
                    </div>

                    <div>
                        Designed By <a href="#" class="text-chromerigs-color">ChromeRigs</a>
                    </div>

                </div>

            </div>

        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.7/js/dataTables.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>